export const FETCH_ARTICLES_FAIL = "FETCH_ARTICLES_FAIL";
export const FETCH_ARTICLES_START = "FETCH_ARTICLES_START";
export const FETCH_ARTICLES_SUCCESS = "FETCH_ARTICLES_SUCCESS";

export const SET_KEYWORD = "SET_KEYWORD";
export const SEARCH_KEYWORD_FAIL = "SEARCH_KEYWORD_FAIL";
export const SEARCH_KEYWORD_START = "SEARCH_KEYWORD";
export const SEARCH_KEYWORD_SUCCESS = "SEARCH_KEYWORD_SUCCESS";
export const SEARCH_FRESH_KEYWORD_SUCCESS = "SEARCH_FRESH_KEYWORD_SUCCESS";

export const START_CONVERSION= "START_CONVERSION";
export const CONVERSION_SUCCESS = "CONVERSION_SUCCESS";
export const CONVERSION_FAIL = "CONVERSION_FAIL";


